---
#
# A Prometheus scrape config
#
global:
  # default scrape interval if not overridden
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ociregistry'
    scrape_interval: 1s
    static_configs:
      - targets:
        - 'localhost:2112'

rule_files:
  - rules.yml