---
#
# A Prometheus scrape config. The 2112 port in targets must
# match what is configured on the command line or the Ociregistry
# config file for the metrics configuration. E.g. --metrics=2112
#
global:
  # default scrape interval if not overridden
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ociregistry'
    # TESTscrape_interval: 15s
    static_configs:
      - targets:
        - 'localhost:2112'

rule_files:
  - rules.yml