{{- if .Values.observability.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "ociregistry.fullname" . }}
  labels:
    {{- include "ociregistry.labels" . | nindent 4 }}
spec:
  groups:
    - name: derived_metrics
      interval: 15s
      rules:
        - record: memory_classes_total_usage_bytes
          expr: memory_classes_total_bytes - memory_classes_heap_released_bytes
{{- end }}
