apiVersion: v1
kind: Service
metadata:
  name: {{ include "ociregistry.fullname" . }}
  labels:
    {{- include "ociregistry.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ociregistry.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
