site_name: Caching Pull-through OCI Distribution Server
site_url: https://aceeric.github.io/ociregistry

nav:
  - Overview: index.md
  - Quick Start (Desktop): quickstart-desktop.md
  - Quick Start (Kubernetes): quickstart-kubernetes.md
  - Configuring The Server: configuring-the-server.md
  - The Command Line: command-line.md
  - Loading And Preloading:  loading.md
  - Pruning The Image Cache: pruning.md
  - Design: design.md
  - Concurrency Design: concur-design.md
  - Airgap Considerations: airgap-considerations.md
  - Administrative REST API: rest-api.md
  - Running as a systemd Service: systemd.md
  - Observability: observability.md
  - Load Testing: load-testing.md
  - Test Driver: test-driver.md
  - Limitations: limitations.md

theme:
  logo: assets/white-logo-no-background.svg
  name: material
  features:
    - navigation.footer
    - content.code.copy

repo_url: https://github.com/aceeric/ociregistry

plugins:
  - search

markdown_extensions:
  - attr_list:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - admonition:
  - pymdownx.details:
  - pymdownx.superfences:

extra_css:
  - extra.css
